name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.9.4
        otp-version: 22.2
    - name: Install Dependencies
      run: mix deps.get
    - name: Install goon
      run: |
        wget https://github.com/alco/goon/releases/download/v1.1.1/goon_linux_amd64.tar.gz
        tar xvfz goon_linux_amd64.tar.gz
    - name: Run Tests
      run: mix test
